# Generated by Django 3.0.5 on 2020-04-04 06:03

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=2021, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
